### ISSUE TITLE
心跳连接超时

### ISSUE THREAD

**Issue by liuht777** [spring-cloud-incubator/spring-cloud-alibaba#329]
Nacos Server 在阿里云上, 确认网络无问题.
Spring Boot 版本: 2.0.5
Spring cloud 版本: Finchley.SR1
spring-cloud-alibaba 版本: 0.2.1.RELEASE

会间歇性的报错心跳失败, ping nacos server ip 网络稳定无问题:
`
[taroco-rbac-service:192.168.120.136:9009] 2019-01-30 11:26:17.535 WARN 11820 [com.alibaba.nacos.naming.beat.sender] com.alibaba.nacos.client.naming [] [] [] failed to request http://118.190.154.85:8848/nacos/v1/ns/api/clientBeat?beat=%7B%22cluster%22%3A%22DEFAULT%22%2C%22dom%22%3A%22taroco-rbac-service%22%2C%22ip%22%3A%22192.168.120.136%22%2C%22metadata%22%3A%7B%7D%2C%22port%22%3A9009%2C%22weight%22%3A1.0%7D&encoding=UTF-8&dom=taroco-rbac-service& from 118.190.154.85
[taroco-rbac-service:192.168.120.136:9009] 2019-01-30 11:26:17.535 ERROR 11820 [com.alibaba.nacos.naming.beat.sender] com.alibaba.nacos.client.naming [] [] [NA] failed to request 

java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
	at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:72)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:290)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:327)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:310)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callAllServers(NamingProxy.java:238)
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[taroco-rbac-service:192.168.120.136:9009] 2019-01-30 11:26:17.536 ERROR 11820 [com.alibaba.nacos.naming.beat.sender] com.alibaba.nacos.client.naming [] [] [CALL-SERVER] failed to req API:http://118.190.154.85:8848/nacos/v1/ns/api/clientBeat. code:500 msg: java.net.SocketTimeoutException: connect timed out
[taroco-rbac-service:192.168.120.136:9009] 2019-01-30 11:26:17.536 ERROR 11820 [com.alibaba.nacos.naming.beat.sender] com.alibaba.nacos.client.naming [] [] [NA] req api:/nacos/v1/ns/api/clientBeat failed, server(118.190.154.85:8848

com.alibaba.nacos.api.exception.NacosException: null
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:327)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:310)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callAllServers(NamingProxy.java:238)
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[taroco-rbac-service:192.168.120.136:9009] 2019-01-30 11:26:17.536 ERROR 11820 [com.alibaba.nacos.naming.beat.sender] com.alibaba.nacos.client.naming [] [] [NA] req api:/nacos/v1/ns/api/clientBeat failed, servers: [118.190.154.85:8848]

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/api/clientBeat after all servers([118.190.154.85:8848]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:335)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:310)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callAllServers(NamingProxy.java:238)
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[taroco-rbac-service:192.168.120.136:9009] 2019-01-30 11:26:17.536 ERROR 11820 [com.alibaba.nacos.naming.beat.sender] com.alibaba.nacos.client.naming [] [] [CLIENT-BEAT] failed to send beat: {"cluster":"DEFAULT","dom":"taroco-rbac-service","ip":"192.168.120.136","metadata":{},"port":9009,"weight":1.0}

java.lang.IllegalStateException: failed to req API:/api//nacos/v1/ns/api/clientBeat after all sites([118.190.154.85:8848]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.callAllServers(NamingProxy.java:247)
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

`

**Comment by Nemo1986** [comment]
请问解决了吗

**Comment by Git4Mark** [comment]
0.2.2同样的问题

**Comment by lkj7b226** [comment]
nacos 版本1.1.3，spring cloud Greenwich.SR2， 一样的问题，心跳检测间歇超时，这玩意能用到生产吗

**Comment by chuntaojun** [comment]
能否linux命令查下nacos-sever端口的tcp连接数信息，可以排查下是不是太多tcp连接了，nacos这里我们也会在后续做相应的优化，降低此类错误的出现概率

**Comment by lkj7b226** [comment]
就起了2个服务测试，也没有接口请求操作，观察2天服务的运行日志发现间歇性的心跳包发送超时，现在打算做下接口请求测试，看心跳的这个超时错误是否会影响接口的正常请求



------------------ 原始邮件 ------------------
发件人: "liaochuntao"<notifications@github.com>; 
发送时间: 2019年9月9日(星期一) 中午11:40
收件人: "alibaba/spring-cloud-alibaba"<spring-cloud-alibaba@noreply.github.com>; 
抄送: "风满楼"<604080160@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [alibaba/spring-cloud-alibaba] 心跳连接超时 (#329)




能否linux命令查下nacos-sever端口的tcp连接数信息，可以排查下是不是太多tcp连接了，nacos这里我们也会在后续做相应的优化，降低此类错误的出现概率

**Comment by 18050012583** [comment]
连接数一直在增长，到最后就会报这个错。

**Comment by chuntaojun** [comment]
在nacos下个版本修复，已发现问题所在

**Comment by guangqan** [comment]
> 在nacos下个版本修复，已发现问题所在

请问是在哪个版本修复的，1.1.4吗？

**Comment by chuntaojun** [comment]
> > 在nacos下个版本修复，已发现问题所在
> 
> 请问是在哪个版本修复的，1.1.4吗？

1.2.0-beta修复了，可以看下

**Comment by dotdotmaples** [comment]
> > > 在nacos下个版本修复，已发现问题所在
> > 
> > 
> > 请问是在哪个版本修复的，1.1.4吗？
> 
> 1.2.0-beta修复了，可以看下

2.2.1发现又注册不上来

**Comment by renmenghao** [comment]
<spring-boot.version>2.2.5.RELEASE</spring-boot.version>
        <spring-cloud.version>Hoxton.SR3</spring-cloud.version>
        <spring-cloud-alibaba.version>2.2.1.RELEASE</spring-cloud-alibaba.version>
存在同样问题呢

**Comment by hoheyho** [comment]
请问下如何解决的呢？我使用的是nacos 2.0.3
<spring-boot.version>2.1.8.RELEASE</spring-boot.version>
<spring-cloud.version>Greenwich</spring-cloud.version>
<spring-cloud-alibaba.version>2.1.2.RELEASE</spring-cloud-alibaba.version>

**Comment by hoheyho** [comment]
请问下如何解决的呢？遇到了同样的问题，我使用的是nacos 2.0.3
<spring-boot.version>2.1.8.RELEASE</spring-boot.version>
<spring-cloud.version>Greenwich</spring-cloud.version>
<spring-cloud-alibaba.version>2.1.2.RELEASE</spring-cloud-alibaba.version>

**Comment by hoheyho** [comment]
> nacos 版本1.1.3，spring cloud Greenwich.SR2， 一样的问题，心跳检测间歇超时，这玩意能用到生产吗

同问，。。。。
