### ISSUE TITLE
nacos config 0.8 and zipkin 2.0.1 Conflict problem

### ISSUE THREAD

**Issue by SessionBest** [spring-cloud-incubator/spring-cloud-alibaba#353]
Desc:
       
     After the configuration is pulled based on config, the error is always reported.

 
The error message is :
    
[AsyncReporter{org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender@44e91298}] ERROR com.alibaba.nacos.client.naming -[] [] [CALL-SERVER] failed to req API:http://127.0.0.1:8848/nacos/v1/ns/api/srvIPXT. code:404 msg: dom not found: 127.0.0.1
2018-12-15 14:25:44.202 [AsyncReporter{org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender@44e91298}] ERROR com.alibaba.nacos.client.naming -[] [] [NA] req api:/nacos/v1/ns/api/srvIPXT failed, server(127.0.0.1:8848
com.alibaba.nacos.api.exception.NacosException: null
at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:308)
at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:331)
at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:314)
at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:262)
at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:330)
at com.alibaba.nacos.client.naming.core.HostReactor.getServiceInfo(HostReactor.java:229)
at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:183)
at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:177)
at org.springframework.cloud.alibaba.nacos.ribbon.NacosServerList.getServers(NacosServerList.java:59)
at org.springframework.cloud.alibaba.nacos.ribbon.NacosServerList.getUpdatedListOfServers(NacosServerList.java:53)
at com.netflix.loadbalancer.DynamicServerListLoadBalancer.updateListOfServers(DynamicServerListLoadBalancer.java:240)
at com.netflix.loadbalancer.DynamicServerListLoadBalancer.restOfInit(DynamicServerListLoadBalancer.java:144)
at com.netflix.loadbalancer.DynamicServerListLoadBalancer.(DynamicServerListLoadBalancer.java:95)
at com.netflix.loadbalancer.ZoneAwareLoadBalancer.(ZoneAwareLoadBalancer.java:82)
at org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration.ribbonLoadBalancer(RibbonClientConfiguration.java:137)
at org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration$$EnhancerBySpringCGLIB$$85ada259.CGLIB$ribbonLoadBalancer$8()
at org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration$$EnhancerBySpringCGLIB$$85ada259$$FastClassBySpringCGLIB$$63d2cad5.invoke()
at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:365)
at org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration$$EnhancerBySpringCGLIB$$85ada259.ribbonLoadBalancer()
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:583)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1246)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1096)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:819)
at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:725)
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:475)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1246)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1096)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:548)
at org.springframework.cloud.context.named.NamedContextFactory.createContext(NamedContextFactory.java:117)
at org.springframework.cloud.context.named.NamedContextFactory.getContext(NamedContextFactory.java:85)
at org.springframework.cloud.netflix.ribbon.SpringClientFactory.getContext(SpringClientFactory.java:118)
at org.springframework.cloud.context.named.NamedContextFactory.getInstance(NamedContextFactory.java:126)
at org.springframework.cloud.netflix.ribbon.SpringClientFactory.getInstance(SpringClientFactory.java:108)
at org.springframework.cloud.netflix.ribbon.SpringClientFactory.getLoadBalancer(SpringClientFactory.java:57)
at org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient.getLoadBalancer(RibbonLoadBalancerClient.java:155)
at org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient.getServer(RibbonLoadBalancerClient.java:144)
at org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient.choose(RibbonLoadBalancerClient.java:76)
at org.springframework.cloud.sleuth.zipkin2.sender.LoadBalancerClientZipkinLoadBalancer.instance(LoadBalancerClientZipkinLoadBalancer.java:42)
at org.springframework.cloud.sleuth.zipkin2.sender.ZipkinRestTemplateSenderConfiguration$1.zipkinUrl(ZipkinRestTemplateSenderConfiguration.java:104)
at org.springframework.cloud.sleuth.zipkin2.sender.ZipkinRestTemplateWrapper.doExecute(ZipkinRestTemplateSenderConfiguration.java:130)
at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:622)
at org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender.post(RestTemplateSender.java:112)
at org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender$HttpPostCall.doExecute(RestTemplateSender.java:123)
at org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender$HttpPostCall.doExecute(RestTemplateSender.java:115)
at zipkin2.Call$Base.execute(Call.java:379)
at zipkin2.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:286)
at zipkin2.reporter.AsyncReporter$Builder$1.run(AsyncReporter.java:190)
2018-12-15 14:25:44.203 [AsyncReporter{org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender@44e91298}] ERROR com.alibaba.nacos.client.naming -[] [] [NA] failed to update serviceName: 127.0.0.1
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/api/srvIPXT after all servers([127.0.0.1:8848]) tried
at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:339)
at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:314)
at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:262)
at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:330)
at com.alibaba.nacos.client.naming.core.HostReactor.getServiceInfo(HostReactor.java:229)
at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:183)
at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:177)
at org.springframework.cloud.alibaba.nacos.ribbon.NacosServerList.getServers(NacosServerList.java:59)
at org.springframework.cloud.alibaba.nacos.ribbon.NacosServerList.getUpdatedListOfServers(NacosServerList.java:53)
at com.netflix.loadbalancer.DynamicServerListLoadBalancer.updateListOfServers(DynamicServerListLoadBalancer.java:240)
at com.netflix.loadbalancer.DynamicServerListLoadBalancer.restOfInit(DynamicServerListLoadBalancer.java:144)
at com.netflix.loadbalancer.DynamicServerListLoadBalancer.(DynamicServerListLoadBalancer.java:95)
at com.netflix.loadbalancer.ZoneAwareLoadBalancer.(ZoneAwareLoadBalancer.java:82)
at org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration.ribbonLoadBalancer(RibbonClientConfiguration.java:137)
at org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration$$EnhancerBySpringCGLIB$$85ada259.CGLIB$ribbonLoadBalancer$8()
at org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration$$EnhancerBySpringCGLIB$$85ada259$$FastClassBySpringCGLIB$$63d2cad5.invoke()
at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:365)
at org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration$$EnhancerBySpringCGLIB$$85ada259.ribbonLoadBalancer()
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:583)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1246)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1096)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:819)
at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:725)
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:475)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1246)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1096)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:548)
at org.springframework.cloud.context.named.NamedContextFactory.createContext(NamedContextFactory.java:117)
at org.springframework.cloud.context.named.NamedContextFactory.getContext(NamedContextFactory.java:85)
at org.springframework.cloud.netflix.ribbon.SpringClientFactory.getContext(SpringClientFactory.java:118)
at org.springframework.cloud.context.named.NamedContextFactory.getInstance(NamedContextFactory.java:126)
at org.springframework.cloud.netflix.ribbon.SpringClientFactory.getInstance(SpringClientFactory.java:108)
at org.springframework.cloud.netflix.ribbon.SpringClientFactory.getLoadBalancer(SpringClientFactory.java:57)
at org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient.getLoadBalancer(RibbonLoadBalancerClient.java:155)
at org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient.getServer(RibbonLoadBalancerClient.java:144)
at org.springframework.cloud.netflix.ribbon.RibbonLoadBalancerClient.choose(RibbonLoadBalancerClient.java:76)
at org.springframework.cloud.sleuth.zipkin2.sender.LoadBalancerClientZipkinLoadBalancer.instance(LoadBalancerClientZipkinLoadBalancer.java:42)
at org.springframework.cloud.sleuth.zipkin2.sender.ZipkinRestTemplateSenderConfiguration$1.zipkinUrl(ZipkinRestTemplateSenderConfiguration.java:104)
at org.springframework.cloud.sleuth.zipkin2.sender.ZipkinRestTemplateWrapper.doExecute(ZipkinRestTemplateSenderConfiguration.java:130)
at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:622)
at org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender.post(RestTemplateSender.java:112)
at org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender$HttpPostCall.doExecute(RestTemplateSender.java:123)
at org.springframework.cloud.sleuth.zipkin2.sender.RestTemplateSender$HttpPostCall.doExecute(RestTemplateSender.java:115)
at zipkin2.Call$Base.execute(Call.java:379)
at zipkin2.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:286)
at zipkin2.reporter.AsyncReporter$Builder$1.run(AsyncReporter.java:190)

**Comment by naturalyui** [comment]
I have also encountered this problem, I have a stupid way to avoid exception information but still did not resolve duplicate requests
## Solution
1. Find [Service Management] - [Service List] on your nacos server
2. Click [Create Service] to fill in your [zipkin] ip or domain name in [Service Name], [Health Check Mode] Fill [Forbidden]
![image](https://user-images.githubusercontent.com/26024263/52841659-cd5e9180-3137-11e9-9df0-727d2e25ad7e.png)

**Comment by SessionBest** [comment]
@naturalyui thank you very mush . but not a good solution. 


@royclarkson  Is there a good solution?

**Comment by SessionBest** [comment]
Don't konw why read the `zipkin.base-url` configuration ...
![image](https://user-images.githubusercontent.com/22487139/52858185-699e8d80-3164-11e9-8542-e9a27e5b5741.png)

**Comment by flystar32** [comment]
@SessionBest  @naturalyui 
I can't reproduce your issue . could you please help to provide a Minimal, Complete, and Verifiable example ?

**Comment by SessionBest** [comment]
**The root pom.xml:**
`<properties>
    <alibaba-cloud.version>0.2.1.RELEASE</alibaba-cloud.version>
    <nacos.version>0.2.1.RELEASE</nacos.version>

    
    
    <zipkin-server.version>2.12.1</zipkin-server.version>
    <zipkin-autoconfigure-ui.version>2.12.1</zipkin-autoconfigure-ui.version>
    <spring-cloud-starter-zipkin.version>2.0.1.RELEASE</spring-cloud-starter-zipkin.version>
    <spring-cloud-starter-sleuth.version>2.0.1.RELEASE</spring-cloud-starter-sleuth.version>
    
  </properties>

       <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-alibaba-dependencies</artifactId>
        <version>${alibaba-cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
  
`
**The Provider code:**

1) pom.xml

`<dependencies>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-zipkin</artifactId>
      <version>${spring-cloud-starter-zipkin.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-sleuth</artifactId>
      <version>${spring-cloud-starter-sleuth.version}</version>
    </dependency>
  </dependencies>`


2)`
@RefreshScope
@RestController
public class RefreshController {

    @Value("${user.age}")
    private int age;
    @Value("${user.name}")
    private String name;

    @SentinelResource(value = "refresh", blockHandler = "handleException", blockHandlerClass = {
        SentinelException.class})
    @RequestMapping("/echo/{str}")
    public String refreshEcho() {
        return age + "--refresh--" + name;
    }


    @RequestMapping("/echo-rest/{str}")
    @SentinelResource(value = "test", blockHandler = "exceptionHandler", fallback = "exceptionFallBack")
    public String test(@PathVariable("str") String str) {
        return age + "--test--" + name;
    }
    public String exceptionFallBack(String s) {
        return String.format("FallbackhelloFallback", s);
    }

    //Block 异常处理函数，参数最后多一个 BlockException，其余与原函数一致

    public static String exceptionHandler(String s, BlockException ex) {
        ex.printStackTrace();
        return "Oops, error occurred at " + s;
    }

}

class SentinelException {

    public static void handleException(BlockException ex) {
        System.out.println("Oops: " + ex.getClass().getCanonicalName());
    }
}`


**The Consumer code:**
1)pom.xml

`<dependencies>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-openfeign</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-zipkin</artifactId>
      <version>${spring-cloud-starter-zipkin.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-sleuth</artifactId>
      <version>${spring-cloud-starter-sleuth.version}</version>
    </dependency>
  </dependencies>`

2)code: 
`
@FeignClient(name = "provider-cloud", fallback = EchoServiceFallback.class, configuration = FeignConfiguration.class)
public interface EchoService {
    @RequestMapping(value = "/echo/{str}", method = RequestMethod.GET)
    String echo(@PathVariable("str") String str);

    @RequestMapping(value = "/divide", method = RequestMethod.GET)
    String divide(@RequestParam("a") Integer a, @RequestParam("b") Integer b);

    @RequestMapping(value = "/notFound", method = RequestMethod.GET)
    String notFound();
}

@Component
public class EchoServiceFallback implements EchoService {

    @Override
    public String echo(@PathVariable("str") String str) {
        return "echo fallback";
    }

    @Override
    public String divide(@RequestParam Integer a, @RequestParam Integer b) {
        return "divide fallback";
    }

    @Override
    public String notFound() {
        return "notFound fallback";
    }
}


public class FeignConfiguration {
    @Bean
    public EchoServiceFallback echoServiceFallback() {
        return new EchoServiceFallback();
    }
}

@RestController
public class FeignController {
    @Autowired
    private EchoService echoService;

    @RequestMapping(value = "/echo-feign/{str}", method = RequestMethod.GET)
    public String feign(@PathVariable String str) {
        return echoService.echo(str);
    }
}
`


**The zipkin server pom.xml:**

`<dependencies>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>io.zipkin.java</groupId>
      <artifactId>zipkin-server</artifactId>
      <version>${zipkin-server.version}</version>
    </dependency>
    <dependency>
      <groupId>io.zipkin.java</groupId>
      <artifactId>zipkin-autoconfigure-ui</artifactId>
      <version>${zipkin-autoconfigure-ui.version}</version>
    </dependency>
  </dependencies>`

**The Nacos config:**

![image](https://user-images.githubusercontent.com/22487139/52946631-6814d580-33af-11e9-9844-da70a4f8aaba.png)
![image](https://user-images.githubusercontent.com/22487139/52946659-782cb500-33af-11e9-972a-1009b75c02d0.png)




Thanks.

**Comment by flystar32** [comment]
@SessionBest  you should configuration `spring.zipkin.discoveryClientEnabled=false` if you wish to send  spans to Zipkin use directly IP address.

**Comment by SessionBest** [comment]
@flystar32  Add the  ` spring.zipkin.discoveryClientEnabled=false ` can be  solved . thanks very mush.

**Comment by Fyuxuan** [comment]
@SessionBest   你好  我想请问下你是就加了 spring.zipkin.discoveryClientEnabled=false 问题就解决了吗  为什么我加了 还是无法解决 下面是我的配置

zipkin:
    discovery-client-enabled: false
    base-url: http://192.168.0.139:9411/
  sleuth:
    sampler:
      probability: 1.0

**Comment by zqWu** [comment]
同样出现了这个问题，使用  spring.zipkin.discoveryClientEnabled=false 或手动注册服务到 nacos上都不能解决 nacos 1.0.1 , spring-cloud finchely (2.0.3)
