### ISSUE TITLE
dubbo services can be registered, but instances cannot run

### ISSUE THREAD

**Issue by halower** [spring-cloud-incubator/spring-cloud-alibaba#440]
```
2019-03-16 11:16:41.425  INFO 14313 --- [           main] org.apache.dubbo.config.AbstractConfig   :  [DUBBO] Register dubbo service org.springframework.cloud.alibaba.dubbo.service.RestService url dubbo://172.19.0.1:20880/org.springframework.cloud.alibaba.dubbo.service.RestService?anyhost=true&application=spring-cloud-alibaba-dubbo-provider&bean.name=ServiceBean:org.springframework.cloud.alibaba.dubbo.service.RestService:1.0.0&bind.ip=172.19.0.1&bind.port=20880&dubbo=2.0.2&generic=false&interface=org.springframework.cloud.alibaba.dubbo.service.RestService&methods=headers,requestBodyUser,pathVariables,form,param,requestBodyMap,params&pid=14313&qos.enable=false&release=2.7.0&revision=1.0.0&side=provider&timestamp=1552706201113&version=1.0.0 to registry registry://localhost:9090/org.apache.dubbo.registry.RegistryService?application=spring-cloud-alibaba-dubbo-provider&dubbo=2.0.2&pid=14313&qos.enable=false&registry=spring-cloud&release=2.7.0&timestamp=1552706201105, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:41.474  INFO 14313 --- [           main] o.a.d.qos.protocol.QosProtocolWrapper    :  [DUBBO] qos won't be started because it is disabled. Please check dubbo.application.qos.enable is configured either in system property, dubbo.properties or XML/spring-boot configuration., dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:41.705  INFO 14313 --- [           main] o.a.d.remoting.transport.AbstractServer  :  [DUBBO] Start NettyServer bind /0.0.0.0:20880, export /172.19.0.1:20880, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:41.714  WARN 14313 --- [           main] o.a.d.c.s.e.SpringExtensionFactory       :  [DUBBO] No spring extension (bean) named:applicationContext, try to find an extension (bean) of type org.springframework.context.ConfigurableApplicationContext, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:41.715  WARN 14313 --- [           main] o.a.d.c.s.e.SpringExtensionFactory       :  [DUBBO] No spring extension (bean) named:applicationContext, type:org.springframework.context.ConfigurableApplicationContext found, stop get bean., dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:41.727  INFO 14313 --- [           main] o.s.c.a.d.registry.SpringCloudRegistry   :  [DUBBO] Register: dubbo://172.19.0.1:20880/org.springframework.cloud.alibaba.dubbo.service.RestService?anyhost=true&application=spring-cloud-alibaba-dubbo-provider&bean.name=ServiceBean:org.springframework.cloud.alibaba.dubbo.service.RestService:1.0.0&dubbo=2.0.2&generic=false&interface=org.springframework.cloud.alibaba.dubbo.service.RestService&methods=headers,requestBodyUser,pathVariables,form,param,requestBodyMap,params&pid=14313&release=2.7.0&revision=1.0.0&side=provider&timestamp=1552706201113&version=1.0.0, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:42.155  INFO 14313 --- [           main] o.s.c.a.n.registry.NacosServiceRegistry  : nacos registry, providers:org.springframework.cloud.alibaba.dubbo.service.RestService:1.0.0 172.19.0.1:20880 register finished
2019-03-16 11:16:42.156  INFO 14313 --- [           main] o.s.c.a.d.registry.SpringCloudRegistry   :  [DUBBO] Subscribe: provider://172.19.0.1:20880/org.springframework.cloud.alibaba.dubbo.service.RestService?anyhost=true&application=spring-cloud-alibaba-dubbo-provider&bean.name=ServiceBean:org.springframework.cloud.alibaba.dubbo.service.RestService:1.0.0&bind.ip=172.19.0.1&bind.port=20880&category=configurators&check=false&dubbo=2.0.2&generic=false&interface=org.springframework.cloud.alibaba.dubbo.service.RestService&methods=headers,requestBodyUser,pathVariables,form,param,requestBodyMap,params&pid=14313&qos.enable=false&release=2.7.0&revision=1.0.0&side=provider&timestamp=1552706201113&version=1.0.0, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:42.419  WARN 14313 --- [           main] o.s.c.a.d.registry.SpringCloudRegistry   :  [DUBBO] Ignore empty notify urls for subscribe url provider://172.19.0.1:20880/org.springframework.cloud.alibaba.dubbo.service.RestService?anyhost=true&application=spring-cloud-alibaba-dubbo-provider&bean.name=ServiceBean:org.springframework.cloud.alibaba.dubbo.service.RestService:1.0.0&bind.ip=172.19.0.1&bind.port=20880&category=configurators&check=false&dubbo=2.0.2&generic=false&interface=org.springframework.cloud.alibaba.dubbo.service.RestService&methods=headers,requestBodyUser,pathVariables,form,param,requestBodyMap,params&pid=14313&qos.enable=false&release=2.7.0&revision=1.0.0&side=provider&timestamp=1552706201113&version=1.0.0, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:42.433  WARN 14313 --- [           main] org.apache.dubbo.config.AbstractConfig   :  [DUBBO] 拒绝连接 (Connection refused), dubbo version: 2.7.0, current host: 172.19.0.1

java.net.ConnectException: 拒绝连接 (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_171]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_171]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_171]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_171]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_171]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_171]
	at org.apache.dubbo.config.ServiceConfig.findConfigedHosts(ServiceConfig.java:636) [dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:510) [dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:402) [dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:363) [dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:345) [dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:318) [dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:112) [dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:58) [dubbo-2.7.0.jar:2.7.0]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) [spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) [spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398) [spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355) [spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:882) [spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) [spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139) [spring-boot-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at org.springframework.cloud.alibaba.dubbo.bootstrap.DubboSpringCloudProviderBootstrap.main(DubboSpringCloudProviderBootstrap.java:33) [classes/:na]

2019-03-16 11:16:42.504  INFO 14313 --- [           main] org.apache.dubbo.config.AbstractConfig   :  [DUBBO] Export dubbo service org.springframework.cloud.alibaba.dubbo.service.RestService to local registry, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:42.505  INFO 14313 --- [           main] org.apache.dubbo.config.AbstractConfig   :  [DUBBO] Export dubbo service org.springframework.cloud.alibaba.dubbo.service.RestService to url rest://172.19.0.1:9090/org.springframework.cloud.alibaba.dubbo.service.RestService?anyhost=true&application=spring-cloud-alibaba-dubbo-provider&bean.name=ServiceBean:org.springframework.cloud.alibaba.dubbo.service.RestService:1.0.0&bind.ip=172.19.0.1&bind.port=9090&dubbo=2.0.2&generic=false&interface=org.springframework.cloud.alibaba.dubbo.service.RestService&methods=headers,requestBodyUser,pathVariables,form,param,requestBodyMap,params&pid=14313&qos.enable=false&release=2.7.0&revision=1.0.0&server=netty&side=provider&timestamp=1552706202425&version=1.0.0, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:42.505  INFO 14313 --- [           main] org.apache.dubbo.config.AbstractConfig   :  [DUBBO] There's no valid monitor config found, if you want to open monitor statistics for Dubbo, please make sure your monitor is configured properly., dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:42.509  INFO 14313 --- [           main] org.apache.dubbo.config.AbstractConfig   :  [DUBBO] Register dubbo service org.springframework.cloud.alibaba.dubbo.service.RestService url rest://172.19.0.1:9090/org.springframework.cloud.alibaba.dubbo.service.RestService?anyhost=true&application=spring-cloud-alibaba-dubbo-provider&bean.name=ServiceBean:org.springframework.cloud.alibaba.dubbo.service.RestService:1.0.0&bind.ip=172.19.0.1&bind.port=9090&dubbo=2.0.2&generic=false&interface=org.springframework.cloud.alibaba.dubbo.service.RestService&methods=headers,requestBodyUser,pathVariables,form,param,requestBodyMap,params&pid=14313&qos.enable=false&release=2.7.0&revision=1.0.0&server=netty&side=provider&timestamp=1552706202425&version=1.0.0 to registry registry://localhost:9090/org.apache.dubbo.registry.RegistryService?application=spring-cloud-alibaba-dubbo-provider&dubbo=2.0.2&pid=14313&qos.enable=false&registry=spring-cloud&release=2.7.0&timestamp=1552706201105, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:42.510  INFO 14313 --- [           main] o.a.d.qos.protocol.QosProtocolWrapper    :  [DUBBO] qos won't be started because it is disabled. Please check dubbo.application.qos.enable is configured either in system property, dubbo.properties or XML/spring-boot configuration., dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:43.238  INFO 14313 --- [           main] o.s.c.a.d.registry.SpringCloudRegistry   :  [DUBBO] Register: rest://172.19.0.1:9090/org.springframework.cloud.alibaba.dubbo.service.RestService?anyhost=true&application=spring-cloud-alibaba-dubbo-provider&bean.name=ServiceBean:org.springframework.cloud.alibaba.dubbo.service.RestService:1.0.0&dubbo=2.0.2&generic=false&interface=org.springframework.cloud.alibaba.dubbo.service.RestService&methods=headers,requestBodyUser,pathVariables,form,param,requestBodyMap,params&pid=14313&release=2.7.0&revision=1.0.0&server=netty&side=provider&timestamp=1552706202425&version=1.0.0, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:43.256  INFO 14313 --- [           main] o.s.c.a.n.registry.NacosServiceRegistry  : nacos registry, providers:org.springframework.cloud.alibaba.dubbo.service.RestService:1.0.0 172.19.0.1:9090 register finished
2019-03-16 11:16:43.257  INFO 14313 --- [           main] o.s.c.a.d.registry.SpringCloudRegistry   :  [DUBBO] Subscribe: provider://172.19.0.1:9090/org.springframework.cloud.alibaba.dubbo.service.RestService?anyhost=true&application=spring-cloud-alibaba-dubbo-provider&bean.name=ServiceBean:org.springframework.cloud.alibaba.dubbo.service.RestService:1.0.0&bind.ip=172.19.0.1&bind.port=9090&category=configurators&check=false&dubbo=2.0.2&generic=false&interface=org.springframework.cloud.alibaba.dubbo.service.RestService&methods=headers,requestBodyUser,pathVariables,form,param,requestBodyMap,params&pid=14313&qos.enable=false&release=2.7.0&revision=1.0.0&server=netty&side=provider&timestamp=1552706202425&version=1.0.0, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:43.257  WARN 14313 --- [           main] o.s.c.a.d.registry.SpringCloudRegistry   :  [DUBBO] Ignore empty notify urls for subscribe url provider://172.19.0.1:9090/org.springframework.cloud.alibaba.dubbo.service.RestService?anyhost=true&application=spring-cloud-alibaba-dubbo-provider&bean.name=ServiceBean:org.springframework.cloud.alibaba.dubbo.service.RestService:1.0.0&bind.ip=172.19.0.1&bind.port=9090&category=configurators&check=false&dubbo=2.0.2&generic=false&interface=org.springframework.cloud.alibaba.dubbo.service.RestService&methods=headers,requestBodyUser,pathVariables,form,param,requestBodyMap,params&pid=14313&qos.enable=false&release=2.7.0&revision=1.0.0&server=netty&side=provider&timestamp=1552706202425&version=1.0.0, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:43.385  INFO 14313 --- [           main] .a.d.b.DubboSpringCloudProviderBootstrap : Started DubboSpringCloudProviderBootstrap in 10.479 seconds (JVM running for 11.247)
2019-03-16 11:16:43.403  INFO 14313 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-03-16 11:16:43.410  INFO 14313 --- [           main] .b.c.e.AwaitingNonWebApplicationListener :  [Dubbo] Current Spring Boot Application is about to shutdown...
2019-03-16 11:16:43.413  INFO 14313 --- [           main] o.a.d.r.support.AbstractRegistryFactory  :  [DUBBO] Close all registries [], dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:43.414  INFO 14313 --- [           main] o.a.d.rpc.protocol.dubbo.DubboProtocol   :  [DUBBO] Close dubbo server: /172.19.0.1:20880, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:43.421  INFO 14313 --- [           main] o.a.d.remoting.transport.AbstractServer  :  [DUBBO] Close NettyServer bind /0.0.0.0:20880, export /172.19.0.1:20880, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:43.426  INFO 14313 --- [           main] o.a.d.rpc.protocol.dubbo.DubboProtocol   :  [DUBBO] Unexport service: dubbo://172.19.0.1:20880/org.springframework.cloud.alibaba.dubbo.service.RestService?anyhost=true&application=spring-cloud-alibaba-dubbo-provider&bean.name=ServiceBean:org.springframework.cloud.alibaba.dubbo.service.RestService:1.0.0&bind.ip=172.19.0.1&bind.port=20880&dubbo=2.0.2&generic=false&interface=org.springframework.cloud.alibaba.dubbo.service.RestService&methods=headers,requestBodyUser,pathVariables,form,param,requestBodyMap,params&pid=14313&qos.enable=false&release=2.7.0&revision=1.0.0&side=provider&timestamp=1552706201113&version=1.0.0, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:43.426  INFO 14313 --- [           main] o.a.d.rpc.protocol.injvm.InjvmProtocol   :  [DUBBO] Unexport service: injvm://127.0.0.1/org.springframework.cloud.alibaba.dubbo.service.RestService?anyhost=true&application=spring-cloud-alibaba-dubbo-provider&bean.name=ServiceBean:org.springframework.cloud.alibaba.dubbo.service.RestService:1.0.0&bind.ip=172.19.0.1&bind.port=9090&dubbo=2.0.2&generic=false&interface=org.springframework.cloud.alibaba.dubbo.service.RestService&methods=headers,requestBodyUser,pathVariables,form,param,requestBodyMap,params&pid=14313&qos.enable=false&release=2.7.0&revision=1.0.0&server=netty&side=provider&timestamp=1552706202425&version=1.0.0, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:43.427  INFO 14313 --- [           main] o.s.c.a.d.registry.SpringCloudRegistry   :  [DUBBO] Unregister: dubbo://172.19.0.1:20880/org.springframework.cloud.alibaba.dubbo.service.RestService?anyhost=true&application=spring-cloud-alibaba-dubbo-provider&bean.name=ServiceBean:org.springframework.cloud.alibaba.dubbo.service.RestService:1.0.0&dubbo=2.0.2&generic=false&interface=org.springframework.cloud.alibaba.dubbo.service.RestService&methods=headers,requestBodyUser,pathVariables,form,param,requestBodyMap,params&pid=14313&release=2.7.0&revision=1.0.0&side=provider&timestamp=1552706201113&version=1.0.0, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:43.429  INFO 14313 --- [           main] o.s.c.a.n.registry.NacosServiceRegistry  : De-registering from Nacos Server now...
2019-03-16 11:16:43.446  INFO 14313 --- [           main] o.s.c.a.n.registry.NacosServiceRegistry  : De-registration finished.
2019-03-16 11:16:43.447  INFO 14313 --- [           main] o.s.c.a.d.registry.SpringCloudRegistry   :  [DUBBO] Unsubscribe: provider://172.19.0.1:20880/org.springframework.cloud.alibaba.dubbo.service.RestService?anyhost=true&application=spring-cloud-alibaba-dubbo-provider&bean.name=ServiceBean:org.springframework.cloud.alibaba.dubbo.service.RestService:1.0.0&bind.ip=172.19.0.1&bind.port=20880&category=configurators&check=false&dubbo=2.0.2&generic=false&interface=org.springframework.cloud.alibaba.dubbo.service.RestService&methods=headers,requestBodyUser,pathVariables,form,param,requestBodyMap,params&pid=14313&qos.enable=false&release=2.7.0&revision=1.0.0&side=provider&timestamp=1552706201113&version=1.0.0, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:43.458  INFO 14313 --- [export-thread-1] o.a.d.r.integration.RegistryProtocol     :  [DUBBO] Waiting 10000ms for registry to notify all consumers before unexport. Usually, this is called when you use dubbo API, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:43.459  INFO 14313 --- [           main] o.s.c.a.d.registry.SpringCloudRegistry   :  [DUBBO] Unregister: rest://172.19.0.1:9090/org.springframework.cloud.alibaba.dubbo.service.RestService?anyhost=true&application=spring-cloud-alibaba-dubbo-provider&bean.name=ServiceBean:org.springframework.cloud.alibaba.dubbo.service.RestService:1.0.0&dubbo=2.0.2&generic=false&interface=org.springframework.cloud.alibaba.dubbo.service.RestService&methods=headers,requestBodyUser,pathVariables,form,param,requestBodyMap,params&pid=14313&release=2.7.0&revision=1.0.0&server=netty&side=provider&timestamp=1552706202425&version=1.0.0, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:43.460  INFO 14313 --- [           main] o.s.c.a.n.registry.NacosServiceRegistry  : De-registering from Nacos Server now...
2019-03-16 11:16:43.472  INFO 14313 --- [           main] o.s.c.a.n.registry.NacosServiceRegistry  : De-registration finished.
2019-03-16 11:16:43.472  INFO 14313 --- [           main] o.s.c.a.d.registry.SpringCloudRegistry   :  [DUBBO] Unsubscribe: provider://172.19.0.1:9090/org.springframework.cloud.alibaba.dubbo.service.RestService?anyhost=true&application=spring-cloud-alibaba-dubbo-provider&bean.name=ServiceBean:org.springframework.cloud.alibaba.dubbo.service.RestService:1.0.0&bind.ip=172.19.0.1&bind.port=9090&category=configurators&check=false&dubbo=2.0.2&generic=false&interface=org.springframework.cloud.alibaba.dubbo.service.RestService&methods=headers,requestBodyUser,pathVariables,form,param,requestBodyMap,params&pid=14313&qos.enable=false&release=2.7.0&revision=1.0.0&server=netty&side=provider&timestamp=1552706202425&version=1.0.0, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:43.475  INFO 14313 --- [           main] o.a.d.rpc.protocol.rest.RestProtocol     :  [DUBBO] Unexport service: rest://172.19.0.1:9090/org.springframework.cloud.alibaba.dubbo.service.RestService?anyhost=true&application=spring-cloud-alibaba-dubbo-provider&bean.name=ServiceBean:org.springframework.cloud.alibaba.dubbo.service.RestService:1.0.0&bind.ip=172.19.0.1&bind.port=9090&dubbo=2.0.2&generic=false&interface=org.springframework.cloud.alibaba.dubbo.service.RestService&methods=headers,requestBodyUser,pathVariables,form,param,requestBodyMap,params&pid=14313&qos.enable=false&release=2.7.0&revision=1.0.0&server=netty&side=provider&timestamp=1552706202425&version=1.0.0, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:43.477  INFO 14313 --- [           main] o.a.d.rpc.protocol.rest.RestProtocol     :  [DUBBO] Closing the rest server at 0.0.0.0:9090, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:43.485  INFO 14313 --- [export-thread-1] o.a.d.r.integration.RegistryProtocol     :  [DUBBO] Waiting 10000ms for registry to notify all consumers before unexport. Usually, this is called when you use dubbo API, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:43.860  INFO 14313 --- [           main] o.a.d.rpc.protocol.rest.RestProtocol     :  [DUBBO] Closing rest clients, dubbo version: 2.7.0, current host: 172.19.0.1
2019-03-16 11:16:43.900  INFO 14313 --- [           main] o.s.c.a.d.s.DubboGenericServiceFactory   : The Dubbo GenericService ReferenceBeans are destroying...
2019-03-16 11:16:43.903  INFO 14313 --- [           main] f.a.ReferenceAnnotationBeanPostProcessor : class org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor was destroying!
2019-03-16 11:16:43.917 ERROR 14313 --- [           main] o.s.boot.SpringApplication               : Application run failed

```

**Comment by halower** [comment]
```
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/service/list after all servers([127.0.0.1:8848]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:374) ~[nacos-client-0.9.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:347) ~[nacos-client-0.9.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:290) ~[nacos-client-0.9.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:272) ~[nacos-client-0.9.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:249) ~[nacos-client-0.9.1.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:406) ~[nacos-client-0.9.1.jar:na]
	at org.springframework.cloud.alibaba.nacos.discovery.NacosWatch.nacosServicesWatch(NacosWatch.java:127) ~[classes/:na]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]

2019-03-16 11:16:41.177  WARN 14313 --- [           main] org.apache.dubbo.config.AbstractConfig   :  [DUBBO] 拒绝连接 (Connection refused), dubbo version: 2.7.0, current host: 172.19.0.1

java.net.ConnectException: 拒绝连接 (Connection refused)

```

**Comment by fangjian0423** [comment]
I think you could build the spring cloud alibaba project firstly.

**Comment by halower** [comment]
It's all right, it's caused by  the local environment  exception,thanks


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
