### ISSUE TITLE
which version is nacos for spring -cloud -gateway ?0.2.2.BUILD-SNAPSHOT?

### ISSUE THREAD

**Issue by vikenlove** [spring-cloud-incubator/spring-cloud-alibaba#464]
when i use 0.2.2.BUILD-SNAPSHOT to create spring-cloud-gateway 

ERROR : 

`ERROR 9884 --- [           main] o.s.c.a.n.registry.NacosServiceRegistry  : nacos registry, server-gateway register failed...NacosRegistration{nacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='127.0.0.1:8848', endpoint='', namespace='', watchDelay=5000, logName='', service='server-gateway', weight=1.0, clusterName='DEFAULT', namingLoadCacheAtStart='false', metadata={}, registerEnabled=true, ip='169.254.23.227', networkInterface='', port=2001, secure=false, accessKey='', secretKey=''}},

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([127.0.0.1:8848]) tried: failed to req API:http://127.0.0.1:8848/nacos/v1/ns/instance. code:500 msg: ErrCode:400,ErrMsg:service not found, namespace: public, service: DEFAULT_GROUP@@server-gateway
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:379) ~[nacos-client-1.0.0-RC1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:303) ~[nacos-client-1.0.0-RC1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:186) ~[nacos-client-1.0.0-RC1.jar:na]`

the nacos-client version is nacos-client-1.0.0-RC1

please  help me

**Comment by vikenlove** [comment]
i was solved it ,beacuse  we need to  add services manually before registering an instance bynacos Console
