### ISSUE TITLE
[.naming.updater] com.alibaba.nacos.client.naming          : [] [] [NA] failed to update serviceName: localhost

### ISSUE THREAD

**Issue by jackemark** [spring-cloud-incubator/spring-cloud-alibaba#470]
2019-03-23 13:53:01.681 ERROR [jmk-gateway,,,] 12372 --- [.naming.updater] com.alibaba.nacos.client.naming          : [] [] [NA] failed to update serviceName: localhost

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/api/srvIPXT after all servers([127.0.0.1:8848]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:335) ~[nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:310) ~[nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:257) ~[nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:340) ~[nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:429) [nacos-client-0.6.2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

**Comment by flystar32** [comment]
which version of nacos server are you using ?

**Comment by umi-soft** [comment]
on master branch， yesterday， following course from nacos.io

**Comment by jackemark** [comment]
0.9.0发自我的华为手机-------- 原始邮件 --------主题：Re: [spring-cloud-incubator/spring-cloud-alibaba] [.naming.updater] com.alibaba.nacos.client.naming          : [] [] [NA] failed to update serviceName: localhost (#470)发件人：xiaojing 收件人：spring-cloud-incubator/spring-cloud-alibaba 抄送：jackemark ,Author which version of nacos server are you using ?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/spring-cloud-incubator/spring-cloud-alibaba","title":"spring-cloud-incubator/spring-cloud-alibaba","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/spring-cloud-incubator/spring-cloud-alibaba"}},"updates":{"snippets":[{"icon":"PERSON","message":"@flystar32 in #470: which version of nacos server are you using ?"}],"action":{"name":"View Issue","url":"https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/470#issuecomment-476029899"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/470#issuecomment-476029899",
"url": "https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/470#issuecomment-476029899",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by flystar32** [comment]
this version are Incompatible, update version to 1.0.0-RC2, I think this is an issue of Nacos.
