### ISSUE TITLE
code:404 msg: service not found: DEFAULT_GROUP@@null

### ISSUE THREAD

**Issue by hyw520110** [spring-cloud-incubator/spring-cloud-alibaba#533]
应用启动报错：
2019-04-08 17:10:37.587 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming[NamingProxy.java:370] -- request 192.168.1.136:8848 failed.
 com.alibaba.nacos.api.exception.NacosException: failed to req API:http://192.168.1.136:8848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@null
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367)
2019-04-08 17:10:37.588 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming[HostReactor.java:278] -- [NA] failed to update serviceName: DEFAULT_GROUP@@null
 java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/list after all servers([192.168.1.130:8848, 192.168.1.136:8848, 192.168.1.202:8848]) tried: failed to req API:http://192.168.1.136:8848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@null
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
2019-04-08 17:10:38.814 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming[NamingProxy.java:370] -- request 192.168.1.202:8848 failed.
 com.alibaba.nacos.api.exception.NacosException: failed to req API:http://192.168.1.202:8848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@null
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367)
2019-04-08 17:10:39.050 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming[NamingProxy.java:370] -- request 192.168.1.130:8848 failed.
 com.alibaba.nacos.api.exception.NacosException: failed to req API:http://192.168.1.130:8848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@null
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367)
2019-04-08 17:10:39.295 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming[NamingProxy.java:370] -- request 192.168.1.136:8848 failed.
 com.alibaba.nacos.api.exception.NacosException: failed to req API:http://192.168.1.136:8848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@null
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367)
2019-04-08 17:10:39.296 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming[HostReactor.java:278] -- [NA] failed to update serviceName: DEFAULT_GROUP@@null
 java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/list after all servers([192.168.1.130:8848, 192.168.1.136:8848, 192.168.1.202:8848]) tried: failed to req API:http://192.168.1.136:8848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@null
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)

依赖版本：
<spring-boot.version>2.1.2.RELEASE</spring-boot.version>
		<spring-cloud.version>Greenwich.RELEASE</spring-cloud.version>
		<spring-cloud-build.version>2.1.2.RELEASE</spring-cloud-build.version>
		<spring-cloud-alibaba.version>2.1.0.BUILD-SNAPSHOT</spring-cloud-alibaba.version>
		<dubbo.version>2.7.0</dubbo.version>
		<spring-cloud-commons.version>2.1.0.RELEASE</spring-cloud-commons.version>

<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>${spring-boot.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-alibaba-dependencies</artifactId>
				<version>${spring-cloud-alibaba.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-commons-dependencies</artifactId>
				<version>${spring-cloud-commons.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
				
			<dependency>
				<groupId>org.apache.dubbo</groupId>
				<artifactId>dubbo-dependencies-bom</artifactId>
				<version>${dubbo.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
	</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>com.big.box</groupId>
			<artifactId>gateway-api</artifactId>
			<version>${project.version}</version>
		</dependency>
		 <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-actuator-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-commons</artifactId>
        </dependency>
         <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-context</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-dubbo</artifactId>
        </dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
		</dependency>
</dependencies>

bootstrap.yml:

server: 
 port: '@server-port@'
spring: 
  application:
    name: '@project.build.finalName@'
  profiles:
      active: '@profile@'
  cloud:   
    nacos:  
      config:   
        enabled: true 
        server-addr: '@server-addr@'
        shared-dataids: application.properties,application-@profile@.properties
      discovery:  
        enabled: true  
        server-addr: '@server-addr@' 
        register-enabled: true
dubbo:
  registry: 
    address: spring-cloud://'@server-addr@' 
  protocol: 
    port: '@dubbo-port@'

nacos server(集群):1.0.0-RC3

**Comment by flystar32** [comment]
Could you please help to provide an Minimal, Complete, and Verifiable example ?
