### ISSUE TITLE
Sentinel client application error parsing json formatted rules into objects

### ISSUE THREAD

**Issue by zhangtianhao** [spring-cloud-incubator/spring-cloud-alibaba#564]
**Which Component**
Sentinel

**Describe the bug**
After adding flow control rules to the application via Sentinel Dashboard, the application is deserializing the corresponding json data into [FlowRule] (https://github.com/alibaba/Sentinel/blob/master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/FlowRule.java) An error occurred while the object was in use.

**To Reproduce**
1. First the client application and the Sentinel Dashboard use the same Zookeeper
2. Use the Arthas tool to diagnose client applications. Monitoring **`com.fasterxml.jackson.databind.ObjectMapper#readValue`** Method execution.
```
watch com.fasterxml.jackson.databind.ObjectMapper readValue '{params, returnObj, throwExp}' -x 2
```
3. Add a flow control rule on the Sentinel Dashboard.
4. Observe the output of Arthas to see the error message
```
ts=2019-04-18 15:51:09; [cost=0.324774ms] result=@ArrayList[
    @Object[][     @String[{"app":"xxx","gmtModified":1555572942154,"resource":"com.xx.yy.ZZZZService:function(com.xx.yy.Ttt)","ip":"172.18.0.9","controlBehavior":0,"count":10.0,"gmtCreate":1555572942154,"limitApp":"default","clusterMode":false,"port":8719,"grade":1,"id":13,"strategy":0}],
        @Class[class com.alibaba.csp.sentinel.slots.block.flow.FlowRule],
    ],
    null,
    com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "app" (class com.alibaba.csp.sentinel.slots.block.flow.FlowRule), not marked as ignorable (12 known properties: "warmUpPeriodSec", "refResource", "rater", "strategy", "limitApp", "grade", "maxQueueingTimeMs", "clusterConfig", "clusterMode", "resource", "count", "controlBehavior"])
 at [Source: {"app":"xxx","gmtModified":1555572942154,"resource":"com.xx.yy.ZZZZService:function(com.xx.yy.Ttt)","ip":"172.18.0.9","controlBehavior":0,"count":10.0,"gmtCreate":1555572942154,"limitApp":"default","clusterMode":false,"port":8719,"grade":1,"id":13,"strategy":0}; line: 1, column: 9] (through reference chain: com.alibaba.csp.sentinel.slots.block.flow.FlowRule["app"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:834)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1093)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1489)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1467)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:282)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2858)
	at org.springframework.cloud.alibaba.sentinel.datasource.converter.JsonConverter.convertFlowRule(JsonConverter.java:115)
	at org.springframework.cloud.alibaba.sentinel.datasource.converter.JsonConverter.convert(JsonConverter.java:70)
	at org.springframework.cloud.alibaba.sentinel.datasource.converter.JsonConverter.convert(JsonConverter.java:38)
	at com.alibaba.csp.sentinel.datasource.AbstractDataSource.loadConfig(AbstractDataSource.java:48)
	at com.alibaba.csp.sentinel.datasource.AbstractDataSource.loadConfig(AbstractDataSource.java:44)
	at com.alibaba.csp.sentinel.datasource.zookeeper.ZookeeperDataSource$1.nodeChanged(ZookeeperDataSource.java:108)
	at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:310)
	at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:304)
	at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
,
]
```
5. Eventually the flow control rules did not take effect.

**Expected behavior**
Json can be successfully parsed into [FlowRule] (https://github.com/alibaba/Sentinel/blob/master/sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/block/flow/FlowRule.java) object.
The flow control rule takes effect.

**Screenshots**
![image](https://user-images.githubusercontent.com/11290981/56348125-61aca980-61f8-11e9-9821-08c4398eb252.png)

**Additional context**
springboot 1.5.3
java8
docker
Sentinel Dashboard 1.4.0
sentinel-datasource-zookeeper 1.5.1
sentinel-transport-simple-http 1.5.1
spring-cloud-starter-alibaba-sentinel 0.1.1.RELEASE

**Comment by fangjian0423** [comment]
Could you put the configuration of applicatoin.properties or application.yaml and the json data of rules here?

**Comment by zhangtianhao** [comment]
# The following is a configuration of sentinel, the application is based on docker-compose.
```
# sentinel
spring.cloud.sentinel.transport.dashboard = sentinel-dashboard:8181
# flow
spring.cloud.sentinel.datasource.flow.zk.server-addr = zookeeper:2181
spring.cloud.sentinel.datasource.flow.zk.path = /sentinel/rules/${spring.application.name}/flow
# degrade
spring.cloud.sentinel.datasource.degrade.zk.server-addr = zookeeper:2181
spring.cloud.sentinel.datasource.degrade.zk.path = /sentinel/rules/${spring.application.name}/degrade
# param
spring.cloud.sentinel.datasource.param-flow.zk.server-addr = zookeeper:2181
spring.cloud.sentinel.datasource.param-flow.zk.path = /sentinel/rules/${spring.application.name}/param
# system
spring.cloud.sentinel.datasource.system.zk.server-addr = zookeeper:2181
spring.cloud.sentinel.datasource.system.zk.path = /sentinel/rules/${spring.application.name}/system
# authority
spring.cloud.sentinel.datasource.authority.zk.server-addr = zookeeper:2181
spring.cloud.sentinel.datasource.authority.zk.path = /sentinel/rules/${spring.application.name}/authority
```
Json data is as follows
`[{"app":"app","clusterMode":false,"controlBehavior":0,"count":1.0,"gmtCreate":1555990566403,"gmtModified":1555990566403,"grade":1,"id":1,"ip":"172.18.0.7","limitApp":"default","port":8719,"resource":"/api/v1/asset/userAssetInfo","strategy":0}]`

**Comment by fangjian0423** [comment]
hi @zhangtianhao 

The properties like id, ip, app, port, gmtCreate, gmtModified can'n converter by default converter.

please refer https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/569.

You could modify sentinel dashboard or using custom converter.
