### ISSUE TITLE
sentinel nacos datasource bug

### ISSUE THREAD

**Issue by ShZhengqin** [spring-cloud-incubator/spring-cloud-alibaba#575]
Hi, @fangjian0423 , 我引入最近的Jar包启动后报错：
```

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ds0-sentinel-nacos-datasource': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [org.springframework.cloud.alibaba.sentinel.datasource.factorybean.NacosDataSourceFactoryBean] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:265) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1253) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1168) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.cloud.alibaba.sentinel.custom.SentinelDataSourceHandler.registerBean(SentinelDataSourceHandler.java:182) ~[spring-cloud-alibaba-sentinel-0.9.0.RELEASE.jar:0.9.0.RELEASE]
	at org.springframework.cloud.alibaba.sentinel.custom.SentinelDataSourceHandler.lambda$afterSingletonsInstantiated$0(SentinelDataSourceHandler.java:72) ~[spring-cloud-alibaba-sentinel-0.9.0.RELEASE.jar:0.9.0.RELEASE]
	at java.util.TreeMap.forEach(Unknown Source) ~[na:1.8.0_171]
	at org.springframework.cloud.alibaba.sentinel.custom.SentinelDataSourceHandler.afterSingletonsInstantiated(SentinelDataSourceHandler.java:60) ~[spring-cloud-alibaba-sentinel-0.9.0.RELEASE.jar:0.9.0.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:866) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at com.services.demo.ServiceDemoApplication.main(ServiceDemoApplication.java:12) ~[classes/:na]
Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.springframework.cloud.alibaba.sentinel.datasource.factorybean.NacosDataSourceFactoryBean] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:686) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:583) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:568) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:248) ~[spring-beans-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	... 22 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/alibaba/csp/sentinel/datasource/nacos/NacosDataSource
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_171]
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[na:1.8.0_171]
	at java.lang.Class.getDeclaredMethods(Unknown Source) ~[na:1.8.0_171]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:668) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	... 25 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource
	at java.net.URLClassLoader.findClass(Unknown Source) ~[na:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_171]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[na:1.8.0_171]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_171]
	... 29 common frames omitted
```

pom.xml文件如下：
```
<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.1.3.RELEASE</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.services.demo</groupId>
	<artifactId>service-demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>war</packaging>
	<name>service-demo</name>
	<description>service demo</description>

	<properties>
		<java.version>1.8</java.version>
		<spring-cloud.version>Finchley.SR2</spring-cloud.version>
		<spring-boot-admin.version>2.1.4</spring-boot-admin.version>
		<spring-cloud-alibaba.version>0.9.0.RELEASE</spring-cloud-alibaba.version>
		<sentinel-datasource-nacos.version>1.5.2</sentinel-datasource-nacos.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter-alibaba-nacos-config -->
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
			<version>${spring-cloud-alibaba.version}</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter-alibaba-nacos-discovery -->
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
			<version>${spring-cloud-alibaba.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<!-- http://codecentric.github.io/spring-boot-admin/2.0.4/ -->
		<dependency>
			<groupId>de.codecentric</groupId>
			<artifactId>spring-boot-admin-starter-client</artifactId>
			<version>${spring-boot-admin.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>

		<!-- sentinel -->
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
			<version>${spring-cloud-alibaba.version}</version>
		</dependency>
		
		<!-- https://mvnrepository.com/artifact/com.alibaba.csp/sentinel-datasource-nacos -->
		<dependency>
		    <groupId>com.alibaba.csp</groupId>
		    <artifactId>sentinel-datasource-nacos</artifactId>
		    <version>${sentinel-datasource-nacos.version}</version>
		    <scope>test</scope>
		</dependency>
				

	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>
```

配置文件如下：
```
spring:
  cloud:
    nacos:
      config:
        namespace: 67747088-40f3-49b3-ab58-b08e7efc08f6
        server-addr: localhost:8848
      discovery:
        namespace: 67747088-40f3-49b3-ab58-b08e7efc08f6
        server-addr: localhost:8848

    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      datasource:
        ds0:
          nacos:
            server-addr: localhost:8848
            data-id: service-demo-flow-rules
            group-id: SENTINEL_GROUP
            data-type: json
            rule-type: flow
        ds1:
          nacos:
            server-addr: localhost:8848
            data-id: service-demo-degrade-rules
            group-id: SENTINEL_GROUP
            data-type: json
            rule-type: degrade
        
```

**Comment by fangjian0423** [comment]
Hi @ShZhengqin 

![image](https://user-images.githubusercontent.com/5254035/56488025-b6f5fd00-650f-11e9-94d9-102ec745860a.png)

This is test scope. So you get a NoClassDefFoundError.

**Comment by ShZhengqin** [comment]
@fangjian0423 , thank you very much,  我的失误

**Comment by ShZhengqin** [comment]
@fangjian0423 , 抱歉，还有一个问题依然困扰我
在 https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/315 中已有人提出过， 现在的问题是，如果我用sentinel-dashboard的页面来更新规则时（已按文档和nacos打通，用nacos作为动态数据源），如图：
![图片](https://user-images.githubusercontent.com/28048110/56490080-89f91880-6516-11e9-9113-c0140eaa8c5a.png)
and
![图片](https://user-images.githubusercontent.com/28048110/56489580-c592e300-6514-11e9-8fff-5564ddd03145.png)
那么在nacos上必然会有这3个字段： app, id, gmtModified 更新进来，如图：
![图片](https://user-images.githubusercontent.com/28048110/56489676-11de2300-6515-11e9-9768-7947353b42b5.png)

我本以为加入了rule-type属性后会自动做处理，现在看来还是不行，bug如下：
```
java.lang.IllegalArgumentException: convert 0 rules but there are 1 rules from datasource. RuleClass: FlowRule
	at org.springframework.cloud.alibaba.sentinel.datasource.converter.SentinelConverter.convert(SentinelConverter.java:80) ~[spring-cloud-alibaba-sentinel-datasource-0.9.0.RELEASE.jar:0.9.0.RELEASE]
	at org.springframework.cloud.alibaba.sentinel.datasource.converter.SentinelConverter.convert(SentinelConverter.java:37) ~[spring-cloud-alibaba-sentinel-datasource-0.9.0.RELEASE.jar:0.9.0.RELEASE]
	at com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource$1.receiveConfigInfo(NacosDataSource.java:104) ~[sentinel-datasource-nacos-1.5.2.jar:na]
	at com.alibaba.nacos.client.config.impl.CacheData$1.run(CacheData.java:188) ~[nacos-client-0.8.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_171]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_171]
```

那么，我能想到的解决方案有如下几个：
1、  在nacos上在每次配置时，顺便将这3个字段去掉；
2、  继续改造sentinel， 更新到nacos的时候就过滤掉这3个字段，但如果在nacos更新规则，那么sentinel-dashboard获取的时候，这3个字段就没有了；
3、 在我的应用service-demo中，自定义一个ConvertClass，如sentinel-core-examples中的JsonFlowRuleListConverter.java，然后自己来处理；
4、 等下一个版本处理

请您解惑，万分感谢!

**Comment by fangjian0423** [comment]
在我的应用service-demo中，自定义一个ConvertClass，如sentinel-core-examples中的JsonFlowRuleListConverter.java，然后自己来处理； 

这个方案最简单也最推荐。

**Comment by ShZhengqin** [comment]
@fangjian0423 ,好的， 謝謝

**Comment by lettgers** [comment]
@ShZhengqin 你最后引入的是那个版本的包？

**Comment by ShZhengqin** [comment]
@lettgers ， 由于0.9.0.RELEASE依赖nacos-client.1.0.0版本，而nacos-client.1.0.0版本存在bug: https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/457, 所以我也将版本降级：

- spring-cloud: 2.0.6.RELEASE
- spring-cloud-starter-alibaba-nacos-config.0.2.2.RELEASE
- spring-cloud-starter-alibaba-nacos-discovery.0.2.2.RELEASE
- sentinel-datasource-nacos.1.5.2.RELEASE
由于sentinel-datasource-nacos.1.5.2.RELEASE依赖nacos-client.0.8.0，所以覆盖了nacos-config.0.2.2依赖的nacos-client.1.0.0版本， 测试通过了，  我的pom.xml如下：
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.6.RELEASE</version>
        <relativePath />
    </parent>
    <groupId>com.services.demo</groupId>
    <artifactId>service-demo</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>war</packaging>
    <name>service-demo</name>
    <description>service demo</description>

    <properties>
        <java.version>1.8</java.version>
        <spring-cloud.version>Finchley.SR2</spring-cloud.version>
        <spring-boot-admin.version>2.0.4</spring-boot-admin.version>
        <spring-cloud-alibaba.version>0.2.2.RELEASE</spring-cloud-alibaba.version>
        <sentinel-datasource-nacos.version>1.5.2</sentinel-datasource-nacos.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>${spring-cloud-alibaba.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>${spring-cloud-alibaba.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-starter-client</artifactId>
            <version>${spring-boot-admin.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>

        <!-- sentinel -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
            <version>${spring-cloud-alibaba.version}</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.alibaba.csp/sentinel-datasource-nacos -->
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-nacos</artifactId>
            <version>${sentinel-datasource-nacos.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- 提高版本,默认版本过低 -->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.56</version>
        </dependency>

    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>


</project>

```

**Comment by ShZhengqin** [comment]
@lettgers , 我今天又测试了下， 将spring cloud升级到2.1.3,， 发现只要将nacos-client显示指定为0.9.x版本也能测试通过，看来在nacos-client.1.0.0版本修复bug之前，强制设置nacos-client为0.9.x版本也可以，就是不知道 nacos-client.0.9.x 会不会有隐藏bug。会持续关注此问题。 加入的部分如下：
```
<!-- nacos-client1.0.0版本有bug:nacos-discovery失败,故将版本降低到0.9.x -->
 <dependency>
      <groupId>com.alibaba.nacos</groupId>
      <artifactId>nacos-client</artifactId>
      <version>0.9.1</version>
 </dependency>
```

**Comment by lettgers** [comment]
@ShZhengqin 谢谢  我尝试一下看看效果
