### ISSUE TITLE
dubbo集成nacos时使用zipkin作为链路追踪有问题

### ISSUE THREAD

**Issue by 2538552544** [spring-cloud-incubator/spring-cloud-alibaba#618]
![image](https://user-images.githubusercontent.com/34358825/56879234-5411e200-6a8a-11e9-99a2-0d1c5e90951c.png)
明明没配置DEFAULT_GROUP@@localhost 但这个错误信息一致在刷
未集成能够正常显示访问，集成zipkin做链路追踪时项目启动并未出现问题 调用DubboRPC接口多次访问时  控制台一直报一个错误 但并未影响正常运行，zipkin的ui界面也能够显示出调用链时间。
`com.alibaba.nacos.api.exception.NacosException: failed to req API:http://*********:8846/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@localhost
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by mercyblitz** [comment]
Please focus on the process of this issue: https://github.com/alibaba/nacos/issues/1153

**Comment by nkorange** [comment]
@2538552544 How did you set up your zipkin server?

**Comment by eacdy** [comment]
这是个Spring Cloud Sleuth的Bug，我这篇文章详细分析了原因以及规避方案：
[解决Spring Cloud Alibaba/Spring Cloud整合Zipkin之后的报错问题](http://www.itmuch.com/spring-cloud-alibaba/spring-cloud-alibaba-zipkin-nacos-exception/)
