### ISSUE TITLE
Load balancer does not have available server for client

### ISSUE THREAD

**Issue by nsecn** [spring-cloud-incubator/spring-cloud-alibaba#635]
2019-05-07 17:39:48 [ERROR] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet][175] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: com.netflix.client.ClientException: Load balancer does not have available server for client: nacos-service-xxx] with root cause
com.netflix.client.ClientException: Load balancer does not have available server for client: nacos-service-xxx
at com.netflix.loadbalancer.LoadBalancerContext.getServerFromLoadBalancer(LoadBalancerContext.java:483)
at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:184)
at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180)
at rx.Observable.unsafeSubscribe(Observable.java:10327)

This happens at intervals. Used version SpringCloud Greenwich.RELEASE, SpringBoot 2.1.2.RELEASE, Nacos 1.0.0

**Comment by nsecn** [comment]
Lack of dependence:
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
</dependency>

**Comment by nsecn** [comment]
After testing, I found that the problem still exists.

**Comment by nsecn** [comment]
<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
</dependency>

**Comment by evanyangg** [comment]
@nsecn 老哥解决了么，我使用feign 继承 遇到这种问题
