### ISSUE TITLE
Can't load config correctly from nacos

### ISSUE THREAD

**Issue by crazy6995** [spring-cloud-incubator/spring-cloud-alibaba#636]
When using nacos to dynamically load nacos configuration content by environment (spring.profiles.active), if the nacos configuration contains any Chinese characters, including Chinese comments or Chinese configuration values, an exception will be thrown when the nacos configuration be loaded between the project starting, The exception is as follows:

**Which Component**
Nacos

**Describe the bug**
if the nacos configuration contains any Chinese characters, including Chinese comments or Chinese configuration values will throw yml parse exception.
same: [https://github.com/alibaba/nacos/issues/1111](url)

**To Reproduce**
put some Chinese characters into configuration.

**Expected behavior**

**Screenshots**
none.
```bash
parse data from Nacos error,dataId:iti-auth.yml,data:spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql8.0+
    #    url: jdbc:mysql://iti-mysql:3306/iti_sys?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://${ITI-MYSQL:iti-mysql}:${ITI-MYSQL-PORT:3306}/iti_sys?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: ${ITI-MYSQL-USER:iti}
    password: ${ITI-MYSQL-PWD:iti} # ENC(zOrbFWpHAts+2mykumbL1g==)
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
  #  kafka:
  #    bootstrap-servers: 127.0.0.1:9092
  #    listener:
  #      type: batch
  #    producer:
  #      batch-size: 500
  #      key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #      value-serializer: com.lan.iti.core.logger.serizlizer.FastjsonKafkaSerializer
  #    consumer:
  #      group-id: commonLogList
  #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #      value-deserializer: com.lan.iti.biz.log.core.serializer.FastjsonKafkaDeserializer
  #      auto-offset-reset: earliest
  #      max-poll-records: 500
iti:
  security:
    # '自动注册功能,mmp中文就凉凉了?注释都不行?'
    auto-registration: true,

org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:218) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:136) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanPlain(ScannerImpl.java:1999) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchPlain(ScannerImpl.java:1044) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:399) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:586) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:124) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:123) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:547) ~[snakeyaml-1.23.jar!/:na]
        at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:160) ~[spring-beans-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
        at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:134) ~[spring-beans-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
        at org.springframework.beans.factory.config.YamlPropertiesFactoryBean.createProperties(YamlPropertiesFactoryBean.java:135) ~[spring-beans-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
        at org.springframework.beans.factory.config.YamlPropertiesFactoryBean.getObject(YamlPropertiesFactoryBean.java:115) ~[spring-beans-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
        at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:100) [spring-cloud-alibaba-nacos-config-0.9.1.BUILD-SNAPSHOT.jar!/:0.9.1.BUILD-SNAPSHOT]
        at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:75) [spring-cloud-alibaba-nacos-config-0.9.1.BUILD-SNAPSHOT.jar!/:0.9.1.BUILD-SNAPSHOT]
        at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:179) [spring-cloud-alibaba-nacos-config-0.9.1.BUILD-SNAPSHOT.jar!/:0.9.1.BUILD-SNAPSHOT]
        at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceLocator.loadApplicationConfiguration(NacosPropertySourceLocator.java:155) [spring-cloud-alibaba-nacos-config-0.9.1.BUILD-SNAPSHOT.jar!/:0.9.1.BUILD-SNAPSHOT]
        at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:88) [spring-cloud-alibaba-nacos-config-0.9.1.BUILD-SNAPSHOT.jar!/:0.9.1.BUILD-SNAPSHOT]
        at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:97) [spring-cloud-context-2.1.1.RELEASE.jar!/:2.1.1.RELEASE]
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:649) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
        at com.lan.iti.auth.ITIAuthApplicationKt.main(ITIAuthApplication.kt:25) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_211]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_211]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_211]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_211]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [iti-auth-1.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [iti-auth-1.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [iti-auth-1.0-SNAPSHOT.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [iti-auth-1.0-SNAPSHOT.jar:na]
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(Unknown Source) ~[na:1.8.0_211]
        at sun.nio.cs.StreamDecoder.implRead(Unknown Source) ~[na:1.8.0_211]
        at sun.nio.cs.StreamDecoder.read(Unknown Source) ~[na:1.8.0_211]
        at java.io.InputStreamReader.read(Unknown Source) ~[na:1.8.0_211]
        at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:125) ~[snakeyaml-1.23.jar!/:na]
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:183) ~[snakeyaml-1.23.jar!/:na]
        ... 49 common frames omitted
```

**Additional context**
Windows
Kotlin
nacos-config:0.9.1.BUILD-SNAPSHOT
nacos-server: 1.0.0-RC3
Mysql: 8.0+

**Comment by crazy6995** [comment]
已解决。感谢：@lengleng (不知道它的github)
将运行环境修改为 UTF-8 编码即可

win下: 
cmd中执行：chcp 65001
