### ISSUE TITLE
客户端刷日志

### ISSUE THREAD

**Issue by caojianqiang1984** [spring-cloud-incubator/spring-cloud-alibaba#657]
**Which Component**
org.springframework.cloud:spring-cloud-starter-alibaba-nacos-discovery:0.9.0.RELEASE

**Describe the bug**
只要请求不存在的服务，就会不断刷日志

**To Reproduce**
1. 注入服务发现客户端
    @Autowired
    private DiscoveryClient discoveryClient;
2. 偿试获取一个不存在的服务
    discoveryClient.getInstances("service-i");

**Expected behavior**
获取一个不存在的服务时，就会不断打印日志
11:03:47.307 ERROR [] HostReactor.updateServiceNow:278 [NA] failed to update serviceName: DEFAULT_GROUP@@DBB-Applyjava.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/list after all servers([service.dev.furong.ink:8848]) tried: failed to req API:http://service.dev.furong.ink:8848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@DBB-Apply
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Additional context**
版本号：
Java11  + spring cloud  Greenwich.RELEASE + org.springframework.cloud:spring-cloud-starter-alibaba-nacos-discovery:0.9.0.RELEASE

**Comment by fangjian0423** [comment]
Which version of Nacos Server?

**Comment by fangjian0423** [comment]
Hi. @caojianqiang1984 

This is a normal phenomenon. It will print `code:404 msg: service not found:...` when service not found in nacos.

I think we could create a issue in nacos to discuss whether throw 404 exception when service not found.

Nacos issue: https://github.com/alibaba/nacos/issues

**Comment by caojianqiang1984** [comment]
打印日志很正常，但它是刷日志，每一秒刷一次，刷个不停，直到找到这个服务为止。而这个服务是不存在的，日志会每隔一秒打印一次不停的刷

**Comment by fangjian0423** [comment]
refer https://github.com/alibaba/nacos/issues/1252 and https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/661.
