### ISSUE TITLE
gateway use nacos config ConcurrentModificationException

### ISSUE THREAD

**Issue by Douganer** [spring-cloud-incubator/spring-cloud-alibaba#670]
项目网关采用 Spring cloud gateway、 Nacos Discovery,  Nacos Config组件，启动时发生并发修改异常
具体如下：
   reactor.core.Exceptions$ErrorCallbackNotImplemented: java.util.ConcurrentModificationException
Caused by: java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at reactor.core.publisher.FluxIterable$IterableSubscription.poll(FluxIterable.java:389)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:634)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:540)
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onSubscribe(FluxFlatMap.java:924)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:139)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:63)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7777)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:389)
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:243)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:201)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:335)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:139)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:63)
	at reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:97)
	at reactor.core.publisher.FluxMap.subscribe(FluxMap.java:62)
	at reactor.core.publisher.FluxMap.subscribe(FluxMap.java:62)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7777)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:389)
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:243)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:201)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:335)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:139)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:63)
	at reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:97)
	at reactor.core.publisher.MonoCollectList.subscribe(MonoCollectList.java:59)
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59)
	at reactor.core.publisher.MonoFlattenIterable.subscribe(MonoFlattenIterable.java:101)
	at reactor.core.publisher.FluxMaterialize.subscribe(FluxMaterialize.java:40)
	at reactor.core.publisher.MonoCollectList.subscribe(MonoCollectList.java:59)
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:74)
	at reactor.core.publisher.MonoFlattenIterable.subscribe(MonoFlattenIterable.java:101)
	at reactor.core.publisher.FluxDematerialize.subscribe(FluxDematerialize.java:39)
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7777)
	at reactor.core.publisher.Flux.subscribeWith(Flux.java:7941)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7770)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7734)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7652)
	at org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter.lambda$onApplicationEvent$0(WeightCalculatorWebFilter.java:133)
	at org.springframework.beans.factory.ObjectProvider.ifAvailable(ObjectProvider.java:93)
	at org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter.onApplicationEvent(WeightCalculatorWebFilter.java:133)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.cloud.gateway.route.RouteRefreshListener.reset(RouteRefreshListener.java:68)
	at org.springframework.cloud.gateway.route.RouteRefreshListener.resetIfNeeded(RouteRefreshListener.java:63)
	at org.springframework.cloud.gateway.route.RouteRefreshListener.onApplicationEvent(RouteRefreshListener.java:57)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.cloud.alibaba.nacos.discovery.NacosWatch.lambda$nacosServicesWatch$0(NacosWatch.java:156)
	at com.alibaba.nacos.client.naming.core.EventDispatcher$Notifier.run(EventDispatcher.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748) 

简单跟踪了bug，初步认为是NacosWatch及configRefreshEventListener，并发访问了GatewayProperties对象的routes属性。

其它：在windows不会出现，mac、linux上大概率出现

**Additional context**
 MacOS  、Java8 、 Version 0.9.0.RELEASE

**Comment by fangjian0423** [comment]
Could you please provide a project that reproduces the issue?

**Comment by Douganer** [comment]
I switch Apollo as config server, the exception will happen as well
my project is below：
    https://github.com/Douganer/fw-gateway

**Comment by Douganer** [comment]
WeightCalculatorWebFilter ：
@Override
	public void onApplicationEvent(ApplicationEvent event) {
		if (event instanceof PredicateArgsEvent) {
			handle((PredicateArgsEvent) event);
		}
		else if (event instanceof WeightDefinedEvent) {
			addWeightConfig(((WeightDefinedEvent) event).getWeightConfig());
		}
		else if (event instanceof RefreshRoutesEvent && routeLocator != null) {
			routeLocator.ifAvailable(locator -> locator.getRoutes().subscribe()); // forces
																					// initialization
		}

	}

**Comment by fangjian0423** [comment]
Hi, could you please provide the configurations with dataId=gateway.yml in nacos?

Now it runs well in my local.

**Comment by SweetInk** [comment]
@fangjian0423 
gateway.yml

``` yml
spring:
  cloud:
    gateway:
      routes:
        - id: demo
          uri: lb://demo-service
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
```

You need to be in a unix-like environment to reproduce this exception (eg:mac,linux)

**Comment by Douganer** [comment]
spring:
  cloud:
    gateway:
      routes:
        - id: admin
          uri: lb://dm-erp
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        - id: activity
          uri: lb://dm-activity
          predicates:
            - Path=/activity/**
          filters:
            - StripPrefix=1
        - id: aims
          uri: lb://dm-aims
          predicates:
            - Path=/aims/**
          filters:
            - StripPrefix=1
        - id: capital
          uri: lb://dm-capital
          predicates:
            - Path=/capital/**
          filters:
            - StripPrefix=1
        - id: card
          uri: lb://dm-card
          predicates:
            - Path=/card/**
          filters:
            - StripPrefix=1
        - id: cas
          uri: lb://dm-cas
          predicates:
            - Path=/cas/**
          filters:
            - StripPrefix=1
        - id: contract
          uri: lb://dm-contract
          predicates:
            - Path=/contract/**
          filters:
            - StripPrefix=1
        - id: coupon
          uri: lb://dm-coupon
          predicates:
            - Path=/coupon/**
          filters:
            - StripPrefix=1
        - id: crm
          uri: lb://dm-crm
          predicates:
            - Path=/crm/**
          filters:
            - StripPrefix=1
        - id: face
          uri: lb://dm-crm-face
          predicates:
            - Path=/face/**
          filters:
            - StripPrefix=1
        - id: file
          uri: lb://dm-dfs-server
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1
        - id: finance
          uri: lb://dm-finance
          predicates:
            - Path=/finance/**
          filters:
            - StripPrefix=1
        - id: hr
          uri: lb://dm-hr
          predicates:
            - Path=/oa/hr/**
          filters:
            - StripPrefix=1
        - id: mcar
          uri: lb://dm-mcar
          predicates:
            - Path=/mcar/**
          filters:
            - StripPrefix=1
        - id: member
          uri: lb://dm-member
          predicates:
            - Path=/member/**
          filters:
            - StripPrefix=1
        - id: oa
          uri: lb://dm-oa
          predicates:
            - Path=/oa/**
          filters:
            - StripPrefix=1
        - id: oop
          uri: lb://dm-oop
          predicates:
            - Path=/oop/**
          filters:
            - StripPrefix=1
        - id: order
          uri: lb://dm-order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: pandora
          uri: lb://dm-pandora
          predicates:
            - Path=/pandora/**
          filters:
            - StripPrefix=1
        - id: passport
          uri: lb://dm-passport
          predicates:
            - Path=/passport/**
          filters:
            - StripPrefix=1
        - id: pay
          uri: lb://dm-pay
          predicates:
            - Path=/pay/**
          filters:
            - StripPrefix=1
        - id: performance
          uri: lb://dm-performance
          predicates:
            - Path=/performance/**
          filters:
            - StripPrefix=1
        - id: points
          uri: lb://dm-points
          predicates:
            - Path=/points/**
          filters:
            - StripPrefix=1
        - id: portal
          uri: lb://dm-portal
          predicates:
            - Path=/portal/**
          filters:
            - StripPrefix=1
        - id: promotion
          uri: lb://dm-promotion
          predicates:
            - Path=/promotion/**
          filters:
            - StripPrefix=1
        - id: pstn
          uri: lb://dm-pstn
          predicates:
            - Path=/pstn/**
          filters:
            - StripPrefix=1
        - id: push
          uri: lb://dm-push
          predicates:
            - Path=/push/**
          filters:
            - StripPrefix=1
        - id: rcar
          uri: lb://dm-rcar
          predicates:
            - Path=/rcar/**
          filters:
            - StripPrefix=1
        - id: report
          uri: lb://dm-report
          predicates:
            - Path=/report/**
          filters:
            - StripPrefix=1
        - id: sms
          uri: lb://dm-sms
          predicates:
            - Path=/sms/**
          filters:
            - StripPrefix=1
        - id: stock
          uri: lb://dm-stock
          predicates:
            - Path=/stock/**
          filters:
            - StripPrefix=1
        - id: test
          uri: lb://alibaba-nacos-discovery-server
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
        - id: trace
          uri: lb://dm-trace
          predicates:
            - Path=/trace/**
          filters:
            - StripPrefix=1
        - id: usedcar
          uri: lb://dm-usedcar
          predicates:
            - Path=/usedcar/**
          filters:
            - StripPrefix=1
        - id: ware
          uri: lb://dm-ware
          predicates:
            - Path=/ware/**
          filters:
            - StripPrefix=1
        - id: wechat
          uri: lb://dm-wechat
          predicates:
            - Path=/wechat/**
          filters:
            - StripPrefix=1
        - id: debug
          uri: lb://dm-debug-x
          predicates:
            - Path=/debug/**
          filters:
            - StripPrefix=1

**Comment by fangjian0423** [comment]
yes, i run with local profile in mac about 10 times. 

Everything is ok, include visit http://localhost:8089/demo/test.

local profile bootstrap.yml:

```yaml
server:
  port: 8089
spring:
  application:
    name: fw-gate
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        ext-config:
          - dataId: gateway.yml
            refresh: true
      discovery:
        server-addr: 127.0.0.1:8848

```

**Comment by fangjian0423** [comment]
Please provide the steps that reproduce this exception.

**Comment by SweetInk** [comment]
@fangjian0423 


> Please provide the steps that reproduce this exception.

You need to add more routing specifications to gateway.yml. The more you get, the more you can revisit the problem.

**Comment by Douganer** [comment]
> @fangjian0423
> 
> > Please provide the steps that reproduce this exception.
> 
> You need to add more routing specifications to gateway.yml. The more you get, the more you can revisit the problem.
`RouteRefreshListener
@Override
	public void onApplicationEvent(ApplicationEvent event) {
		if (event instanceof ContextRefreshedEvent
				|| event instanceof RefreshScopeRefreshedEvent
				|| event instanceof InstanceRegisteredEvent) {
			reset();
		}
		else if (event instanceof ParentHeartbeatEvent) {
			ParentHeartbeatEvent e = (ParentHeartbeatEvent) event;
			resetIfNeeded(e.getValue());
		}
		else if (event instanceof HeartbeatEvent) {
			HeartbeatEvent e = (HeartbeatEvent) event;
			resetIfNeeded(e.getValue());
		}
	}

	private void resetIfNeeded(Object value) {
		if (this.monitor.update(value)) {
			reset();
		}
	}

	private void reset() {
		this.publisher.publishEvent(new RefreshRoutesEvent(this));
	}`
`RefreshEventListener
@Override
	public void onApplicationEvent(ApplicationEvent event) {
		if (event instanceof ApplicationReadyEvent) {
			handle((ApplicationReadyEvent) event);
		}
		else if (event instanceof RefreshEvent) {
			handle((RefreshEvent) event);
		}
	}

	public void handle(ApplicationReadyEvent event) {
		this.ready.compareAndSet(false, true);
	}

	public void handle(RefreshEvent event) {
		if (this.ready.get()) { // don't handle events before app is ready
			log.debug("Event received " + event.getEventDesc());
			Set<String> keys = this.refresh.refresh();
			log.info("Refresh keys changed: " + keys);
		}
	}`
`WeightCalculatorWebFilter
@Override
	public void onApplicationEvent(ApplicationEvent event) {
		if (event instanceof PredicateArgsEvent) {
			handle((PredicateArgsEvent) event);
		}
		else if (event instanceof WeightDefinedEvent) {
			addWeightConfig(((WeightDefinedEvent) event).getWeightConfig());
		}
		else if (event instanceof RefreshRoutesEvent && routeLocator != null) {
			routeLocator.ifAvailable(locator -> locator.getRoutes().subscribe()); // forces
																					// initialization
		}

	}`
`NacosWatch
public void nacosServicesWatch() {
		try {

			boolean changed = false;
			NamingService namingService = properties.namingServiceInstance();

			ListView<String> listView = properties.namingServiceInstance()
					.getServicesOfServer(1, Integer.MAX_VALUE);

			List<String> serviceList = listView.getData();

			// if there are new services found, publish event
			Set<String> currentServices = new HashSet<>(serviceList);
			currentServices.removeAll(cacheServices);
			if (currentServices.size() > 0) {
				changed = true;
			}

			// if some services disappear, publish event
			if (cacheServices.removeAll(new HashSet<>(serviceList))
					&& cacheServices.size() > 0) {
				changed = true;

				for (String serviceName : cacheServices) {
					namingService.unsubscribe(serviceName,
							subscribeListeners.get(serviceName));
					subscribeListeners.remove(serviceName);
				}
			}

			cacheServices = new HashSet<>(serviceList);

			// subscribe services's node change, publish event if nodes changed
			for (String serviceName : cacheServices) {
				if (!subscribeListeners.containsKey(serviceName)) {
					EventListener eventListener = event -> NacosWatch.this.publisher
							.publishEvent(new HeartbeatEvent(NacosWatch.this,
									nacosWatchIndex.getAndIncrement()));
					subscribeListeners.put(serviceName, eventListener);
					namingService.subscribe(serviceName, eventListener);

				}
			}

			if (changed) {
				this.publisher.publishEvent(
						new HeartbeatEvent(this, nacosWatchIndex.getAndIncrement()));
			}

		}
		catch (Exception e) {
			log.error("Error watching Nacos Service change", e);
		}
	}`
The above code generates concurrency problems， the more services，the easier bug will appear!

**Comment by Douganer** [comment]
Here's the simple exception steps
1、NacosWach -->nacosServicesWatch()-->publishEvent(new HeartbeatEvent())
2、RouteRefreshListener-->onApplicationEvent(HeartbeatEvent)-->publishEvent(new RefreshRoutesEvent)
3、WeightCalculatorWebFilter-->onApplicationEvent(RefreshRoutesEvent)-->locator.getRoutes().subscribe() 【 produce ConcurrentModificationException】

4、NacosContextRefresher-->onApplicationEvent（ApplicationReadyEvent）-->publishEvent(new RefreshEvent())
5、ClientWorker -->CacheData.checkListenerMd5-->publishEvent(new RefreshEvent())
6、RefreshEventListener-->onApplicationEvent(RefreshEvent)-->refresh.refreshEnvironment() [modify routes]

**Comment by fangjian0423** [comment]
@Douganer hi

I have added 10 routes in yaml, but is didn't reproduce.

Why did you close it?

**Comment by MemoryF** [comment]
I also have this, and the versions are

Spring-cloud-alia-dependencies: 2.2.3.RELEASE, Spring-cloud.version: Hoxton.sr8

**Comment by yang00yang** [comment]
@SweetInk is it finally solved

**Comment by yang00yang** [comment]
@MemoryF Is it finally solved

**Comment by SweetInk** [comment]
@yang00yang 目前无法重现这个异常了。

**Comment by yang00yang** [comment]
@SweetInk 是做了什么操作嘛，还是更换了版本

**Comment by SweetInk** [comment]
> @SweetInk 是做了什么操作嘛，还是更换了版本

同版本，没做啥操作，你能复现吗

**Comment by yang00yang** [comment]
> > @SweetInk 是做了什么操作嘛，还是更换了版本
> 
> 同版本，没做啥操作，你能复现吗

可以呀，每次启动的时候都会报错

**Comment by ZeroMing** [comment]
> Here's the simple exception steps
> 1、NacosWach -->nacosServicesWatch()-->publishEvent(new HeartbeatEvent())
> 2、RouteRefreshListener-->onApplicationEvent(HeartbeatEvent)-->publishEvent(new RefreshRoutesEvent)
> 3、WeightCalculatorWebFilter-->onApplicationEvent(RefreshRoutesEvent)-->locator.getRoutes().subscribe() 【 produce ConcurrentModificationException】
> 
> 4、NacosContextRefresher-->onApplicationEvent（ApplicationReadyEvent）-->publishEvent(new RefreshEvent())
> 5、ClientWorker -->CacheData.checkListenerMd5-->publishEvent(new RefreshEvent())
> 6、RefreshEventListener-->onApplicationEvent(RefreshEvent)-->refresh.refreshEnvironment() [modify routes]

why did you close ？
