### ISSUE TITLE
nacos-config：java.lang.IllegalArgumentException: no server available

### ISSUE THREAD

**Issue by Nemo1986** [spring-cloud-incubator/spring-cloud-alibaba#688]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel
Nacos： 1.0.0
spring-cloud.version： Greenwich.SR1
spring-cloud-alibaba-dependencies：0.9.0.RELEASE

**Describe the bug**
2019-05-31 09:10:59.418 ERROR 17024 --- [           main] o.s.c.a.n.registry.NacosServiceRegistry  : nacos registry, nacos-config-client register failed...NacosRegistration{nacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='', endpoint='', namespace='', watchDelay=30000, logName='', service='nacos-config-client', weight=1.0, clusterName='DEFAULT', namingLoadCacheAtStart='false', metadata={preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='192.168.1.151', networkInterface='', port=8001, secure=false, accessKey='', secretKey=''}},

java.lang.IllegalArgumentException: no server available
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:354) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:186) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:298) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:279) ~[nacos-client-1.0.0.jar:na]
	at org.springframework.cloud.alibaba.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:63) ~[spring-cloud-alibaba-nacos-discovery-0.9.0.RELEASE.jar:0.9.0.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:239) [spring-cloud-commons-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.cloud.alibaba.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:74) [spring-cloud-alibaba-nacos-discovery-0.9.0.RELEASE.jar:0.9.0.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:138) [spring-cloud-commons-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:101) [spring-cloud-commons-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:88) [spring-cloud-commons-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:47) [spring-cloud-commons-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) [spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) [spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402) [spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359) [spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:166) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) [spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at cn.lygnemo.nacosconfigclient.NacosConfigClientApplication.main(NacosConfigClientApplication.java:15) [classes/:na]

**To Reproduce**
启动nacos-config-client后，报错如上，但是配置能正常读取并且在nacos服务上更新参数后也能正常更新。启动完成后每三十秒报一次错：java.lang.IllegalArgumentException: no server available

When nacos-config-client was started, the error was reported as above, but the configuration could be read normally and the parameters could be updated normally after nacos service.Start at every 30 seconds after the completion of a fault: Java. Lang. IllegalArgumentException: no server available

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/8785753/58675350-82832580-8386-11e9-9f0d-bc25f4811687.png)

**Additional context**
e.g.  MacOS  、Java8 、 Version 0.2.1.RELEASE

**Comment by fangjian0423** [comment]
The log shows "nacos registry, nacos-config-client register failed", see the log of nacos-server.

**Comment by Nemo1986** [comment]
naming-server.log


2019-05-31 10:13:53,221 WARN protect threshold reached, return all ips, service: DEFAULT_GROUP@@nacos-provider

2019-05-31 10:13:53,241 INFO [NACOS-RAFT] datum is changed, key: com.alibaba.nacos.naming.iplist.ephemeral.public##DEFAULT_GROUP@@nacos-provider, value: {"cachedChecksum":"","instanceList":[{"app":"DEFAULT","clusterName":"DEFAULT","enabled":true,"ephemeral":true,"healthy":true,"instanceId":"192.168.1.151#8762#DEFAULT#DEFAULT_GROUP@@nacos-provider","ip":"192.168.1.151","lastBeat":1559268833241,"marked":false,"metadata":{"preserved.register.source":"SPRING_CLOUD"},"port":8762,"serviceName":"DEFAULT_GROUP@@nacos-provider","tenant":"","weight":1}]}

2019-05-31 10:13:54,242 WARN protect threshold reached, return all ips, service: DEFAULT_GROUP@@nacos-provider

2019-05-31 10:13:54,251 WARN protect threshold reached, return all ips, service: DEFAULT_GROUP@@nacos-provider

**Comment by fangjian0423** [comment]
It seems your configuration is missing something.

NacosRegistration{nacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='', endpoint='', namespace='', watchDelay=30000, logName='', service='nacos-config-client', weight=1.0, clusterName='DEFAULT', namingLoadCacheAtStart='false', metadata={preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='192.168.1.151', networkInterface='', port=8001, secure=false, accessKey='', secretKey=''}},

Nacos server-add is empty.

Please provide your configurations.

**Comment by Nemo1986** [comment]
![image](https://user-images.githubusercontent.com/8785753/58678567-bf551980-8392-11e9-8b51-a2e96bd5fbd5.png)
![image](https://user-images.githubusercontent.com/8785753/58678610-ed3a5e00-8392-11e9-9603-94f093218065.png)

bootstrap.properties：
spring.application.name=nacos-config-client
server.port=8001
spring.cloud.nacos.config.server-addr=127.0.0.1:8848

**Comment by fangjian0423** [comment]
If you want to use nacos-discovery, pls set `spring.cloud.nacos.discovery.server-addr`, it is different from `spring.cloud.nacos.config.server-addr`.

**Comment by Nemo1986** [comment]
Remove alibaba-nacos-discovery. It's working. Thank you

**Comment by chenp2368** [comment]
你好，请问一下“Remove alibaba-nacos-discovery”，这里没看太懂，希望您能帮忙回复一下。遇到了同样的问题，一直找不到解决的方法。谢谢！

**Comment by woshiawei** [comment]
spring.cloud.nacos.discovery.group=test   is for the nacos registory server
spring.cloud.nacos.config.group=test   is for the nacos config server
there is a "spring.cloud.nacos.config" and "spring.cloud.nacos.discovery" 
maybe you ingored the "discovery" configuration

你可能忽略了discovery 这个配置

**Comment by woshiawei** [comment]
> 你好，请问一下“Remove alibaba-nacos-discovery”，这里没看太懂，希望您能帮忙回复一下。遇到了同样的问题，一直找不到解决的方法。谢谢！

please check my reply!

**Comment by Nemo1986** [comment]
> 
> 
> 你好，请问一下“Remove alibaba-nacos-discovery”，这里没看太懂，希望您能帮忙回复一下。遇到了同样的问题，一直找不到解决的方法。谢谢！

把alibaba-nacos-discovery的配置给删掉，还有maven里的包。
