### ISSUE TITLE
can't launch SpringBoot 1.5.x

### ISSUE THREAD

**Issue by chenshun00** [spring-cloud-incubator/spring-cloud-alibaba#726]
pom.xml

```
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>0.1.0.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>0.1.0.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>1.5.21.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Edgware.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>0.1.2.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

Java 
```
@SpringBootApplication
@EnableDiscoveryClient
public class GatewayApplication {
    public static void main(String[] args) {
        SpringApplication.run(GatewayApplication.class);
    }
}
```

Error:
```
java.lang.NoSuchMethodError: org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.<init>(Lorg/springframework/cloud/client/serviceregistry/ServiceRegistry;Lorg/springframework/cloud/client/serviceregistry/AutoServiceRegistrationProperties;)V
	at org.springframework.cloud.alibaba.nacos.registry.NacosAutoServiceRegistration.<init>(NacosAutoServiceRegistration.java:42) ~[spring-cloud-alibaba-nacos-discovery-0.1.2.RELEASE.jar:0.1.2.RELEASE]
	at org.springframework.cloud.alibaba.nacos.NacosDiscoveryAutoConfiguration.nacosAutoServiceRegistration(NacosDiscoveryAutoConfiguration.java:73) ~[spring-cloud-alibaba-nacos-discovery-0.1.2.RELEASE.jar:0.1.2.RELEASE]
```

Document:

https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

Spring Cloud Version | Spring Cloud Alibaba Version | Spring Boot Version
-- | -- | --
Spring Cloud Greenwich | 0.9.0.RELEASE | 2.1.X.RELEASE
Spring Cloud Finchley | 0.2.X.RELEASE | 2.0.X.RELEASE
Spring Cloud Edgware | 0.1.X.RELEASE | 1.5.X.RELEASE

spring-cloud-alibaba-nacos-discovery-0.1.2.RELEASE.jar:

```
 public NacosAutoServiceRegistration(ServiceRegistry<Registration> serviceRegistry, AutoServiceRegistrationProperties autoServiceRegistrationProperties, NacosRegistration registration) {
        super(serviceRegistry, autoServiceRegistrationProperties);
        this.registration = registration;
    }
```

Spring cloud common: 1.3.0.RELEASE

```
    protected AbstractAutoServiceRegistration(ServiceRegistry<R> serviceRegistry) {
        this.serviceRegistry = serviceRegistry;
    }
```

:(

how to fix it by us 👍 
![image](https://user-images.githubusercontent.com/26037282/60414201-093b5480-9c0a-11e9-9872-4afa5bb21b2f.png)

**Comment by fangjian0423** [comment]
use Edgware.SR5, not Edgware.RELEASE

**Comment by chenshun00** [comment]
it's worked.

**Comment by HSPCode** [comment]
1、problem-description：can't launch SpringBoot 1.5.x
![image](https://user-images.githubusercontent.com/47849395/126617135-5a2e0da6-ab89-4477-90e8-9d16dd3ee9b5.png)

2、pom-version：
<dependency>
      <groupId>org.springframework.boot</groupId>
     <artifactId>spring-boot-parent</artifactId>
     <version>1.5.9.RELEASE</version>
</dependency>
<dependency>
      <groupId>com.alibaba.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
      <version>1.5.1.RELEASE</version>
</dependency>

3、class-method：
package：com.alibaba.cloud.nacos.registry
class：NacosServiceRegistry
method：getNacosInstanceFromRegistration
![image](https://user-images.githubusercontent.com/47849395/126616164-fa959949-6b22-4953-901f-de6103b14a2c.png)
